version: 2
project_patterns:
  exclude_paths:
    - docs/**
    - project/app/db_init/**
    - project/tests/**
analysis:
  language: python
  tools:
    - pylint
    - flake8
    - pyflakes
    - black