FROM python:alpine
COPY requirements.txt .
RUN apk add --no-cache gcc musl-dev python3-dev libffi-dev linux-headers
RUN pip install -r requirements.txt
CMD ["python", "./main.py"]
COPY . .
EXPOSE 8000