FROM python:alpine
WORKDIR /app/app
COPY requirements.txt .
RUN apk add --no-cache gcc musl-dev python3-dev libffi-dev linux-headers
RUN pip install -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["python", "./main.py"]