services:
    pokedb:
        container_name: pokedb
        image: mysql:9.2.0
        ports:
            - "32001:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
            - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

    redis:
        image: redis:8.2-m01-bookworm
        ports:
            - "6379:6379"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 3s
            retries: 5


    app:
        container_name: dexquiz
        build:
            context: .
            dockerfile: dockerfile
        expose:
            - "8000"
        ports:
            - "8000:8000"
        depends_on:
            pokedb:
                condition: service_healthy
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_URL: ${MYSQL_URL}
            HOST_IP: ${HOST_IP}
            REDIS_PORT: ${REDIS_PORT}
            REDIS_HOST: ${REDIS_HOST}
            PYTHONPATH: /app
            USE_TEST_POKEMON: "1"

volumes:
    mysql_data:  # define only the named volume here