---
openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  "/":
    get:
      summary: Home
      description: |-
        Home site.

        Args:
            request (Request): request body

        Returns:
            TemplateResponse: Returns the HTML Template to be displayed in the clients browser.
      operationId: home__get
      responses:
        '200':
          description: Successful Response
          content:
            text/html:
              schema:
                type: string
  "/login":
    get:
      summary: Login Form
      description: |-
        Route for the login-frontend

        Args:
            request (Request): request body

        Returns:
            TemplateResponse: HTML to be displayed in the browser
      operationId: login_form_login_get
      responses:
        '200':
          description: Successful Response
          content:
            text/html:
              schema:
                type: string
  "/register":
    get:
      summary: Register Form
      description: |-
        Register Route. Provides the frontend to give users the opportunity to sell their
           soul to this website.

        Args:
            request (Request): Request

        Returns:
            TemplateResponse: The HTML Template to be displayed
      operationId: register_form_register_get
      responses:
        '200':
          description: Successful Response
          content:
            text/html:
              schema:
                type: string
  "/highscores":
    get:
      summary: Highscore Page
      description: |-
        Highscores Page. Can only be accessed if the user is logged in.
           That is handled in the js code however.

        Args:
            request (Request): reqeust body

        Returns:
            HTMLResponse: Highscores Page to be displayed in the browser.
      operationId: highscore_page_highscores_get
      responses:
        '200':
          description: Successful Response
          content:
            text/html:
              schema:
                type: string
  "/quiz":
    get:
      summary: Get Quiz
      description: |-
        Quiz page. Uses templating cimbined with a fetch from the redis container (where
        the quiz data is stored at) to return a server-side rendered thing

        Args:
            request (Request): reqeust body

        Returns:
            HTMLResponse: Quiz Page (rendered).
      operationId: get_quiz_quiz_get
      responses:
        '200':
          description: Successful Response
          content:
            text/html:
              schema:
                type: string
  "/api/highscores":
    get:
      summary: Get All Highscores
      description: |-
        Returns all highscores in the database.

        Requires user to be authenticated via a JWT token in cookies.

        Args:
            user (UserInDb): The authenticated user.

        Returns:
            List[HighscoreResponse]: A list of all highscores.

        Raises:
            HTTPException: 404 if highscores are not found.
            HTTPException: 500 if a database error occurs.
      operationId: get_all_highscores_api_highscores_get
      parameters:
      - name: access_token
        in: cookie
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Access Token
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/HighscoreResponse"
                title: Response Get All Highscores Api Highscores Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/api/highscore/{top}":
    get:
      summary: Get Top Highscores Api
      description: |-
        "Returns the top N highscores. Requires authentication.

        Args:
            top (int): The number of top scores to retrieve.
            user (UserInDb): The authenticated user (access control only).

        Returns:
            List[HighscoreResponse]: The top N highscores.

        Raises:
            HTTPException: 404 if no highscores are found.
            HTTPException: 500 if a database error occurs.
      operationId: get_top_highscores_api_api_highscore__top__get
      parameters:
      - name: top
        in: path
        required: true
        schema:
          type: integer
          title: Top
      - name: access_token
        in: cookie
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Access Token
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/HighscoreResponse"
                title: Response Get Top Highscores Api Api Highscore  Top  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/api/highscore":
    post:
      summary: Post Highscore
      description: |-
        Submits the user's current score as a highscore.

        Reads score data from Redis using the quiz session ID stored in cookies.
        Validates and stores the highscore in the database. Resets the score in Redis afterward.

        Args:
            request (Request): The HTTP request containing cookies.
            user (UserInDb): The authenticated user submitting the score.

        Returns:
            dict: The newly created highscore record.

        Raises:
            HTTPException: 400 if session ID, quiz data, or score is missing.
            HTTPException: 404 if the highscore could not be created.
            HTTPException: 500 on internal server or database error.
      operationId: post_highscore_api_highscore_post
      parameters:
      - name: access_token
        in: cookie
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Access Token
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/api/token":
    post:
      summary: Login
      description: Login route that returns access and refresh tokens as HTTP-only
        cookies.
      operationId: login_api_token_post
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              "$ref": "#/components/schemas/Body_login_api_token_post"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/api/token/refresh":
    post:
      summary: Refresh Token
      operationId: refresh_token_api_token_refresh_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  "/api/register":
    post:
      summary: Register
      description: |-
        Registers a new user.
        Args:
            request (RegisterRequest): Request

        Raises:
            HTTPException: _description_
      operationId: register_api_register_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/RegisterRequest"
        required: true
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/api/logout":
    post:
      summary: Logout
      operationId: logout_api_logout_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  "/api/username":
    get:
      summary: Get Username
      operationId: get_username_api_username_get
      parameters:
      - name: access_token
        in: cookie
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Access Token
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/api/start_quiz":
    get:
      summary: Start Quiz
      description: |-
        Starts a new quiz session and redirects to the quiz page.

        A unique session ID is generated and stored in an HTTP-only cookie.
        The user is redirected to the `/quiz` frontend route.

        Args:
            response (Response): The response object used to set cookies and redirect.

        Returns:
            RedirectResponse: A 302 redirect response to the quiz page with the session cookie set.
      operationId: start_quiz_api_start_quiz_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  "/api/next_quiz":
    post:
      summary: Next Quiz
      description: |-
        Prepares the next quiz question and updates session state.

        Retrieves the user's current quiz session via cookie, preserves the current score,
        fetches a new Pokémon, and stores it in the session state.

        Args:
            request (Request): The incoming request containing cookies for session tracking.

        Returns:
            JSONResponse: A success message if a session exists, or an error message if not.
      operationId: next_quiz_api_next_quiz_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  "/api/quiz":
    post:
      summary: Post Quiz
      description: |-
        Processes the user's guess and updates the quiz session.

        Checks the submitted answer against the correct Pokémon name.
        Updates the score on a correct guess and prepares hints for incorrect guesses.
        Initializes a new session if none exists.

        Args:
            request (Request): The incoming request containing the session cookie and form data.
            guess (str): The user's guess, submitted via form input.

        Returns:
            JSONResponse: A response indicating whether the guess was correct,
            the updated score, and optional hints.
      operationId: post_quiz_api_quiz_post
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              "$ref": "#/components/schemas/Body_post_quiz_api_quiz_post"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/api/quiz/reset":
    post:
      summary: Reset Quiz Score
      description: |-
        Resets the current quiz score in the session.

        Args:
            request (Request): The incoming request with session cookie.

        Returns:
            JSONResponse: A message confirming the score has been reset.
      operationId: reset_quiz_score_api_quiz_reset_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
components:
  schemas:
    Body_login_api_token_post:
      properties:
        grant_type:
          anyOf:
          - type: string
            pattern: "^password$"
          - type: 'null'
          title: Grant Type
        username:
          type: string
          title: Username
        password:
          type: string
          title: Password
        scope:
          type: string
          title: Scope
          default: ''
        client_id:
          anyOf:
          - type: string
          - type: 'null'
          title: Client Id
        client_secret:
          anyOf:
          - type: string
          - type: 'null'
          title: Client Secret
      type: object
      required:
      - username
      - password
      title: Body_login_api_token_post
    Body_post_quiz_api_quiz_post:
      properties:
        guess:
          type: string
          title: Guess
      type: object
      required:
      - guess
      title: Body_post_quiz_api_quiz_post
    HTTPValidationError:
      properties:
        detail:
          items:
            "$ref": "#/components/schemas/ValidationError"
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    HighscoreResponse:
      properties:
        username:
          type: string
          title: Username
        score:
          type: integer
          title: Score
        achieved_at:
          type: string
          format: date-time
          title: Achieved At
      type: object
      required:
      - username
      - score
      - achieved_at
      title: HighscoreResponse
      description: |-
        Highscore Data Object from the database.

        username (str): extracted Username
        score (int): archived score
        achieved_at: timestamp of when the entry was last modified/created
    RegisterRequest:
      properties:
        username:
          type: string
          title: Username
        password:
          type: string
          title: Password
      type: object
      required:
      - username
      - password
      title: RegisterRequest
      description: "Model for User\n    "
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
