name: UI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    env:
      USE_TEST_POKEMON: "1"
      MYSQL_ROOT_PASSWORD: pokeballs
      MYSQL_DATABASE: pokedb
      MYSQL_USER: trainer
      MYSQL_PASSWORD: pokeballs
      MYSQL_URL: pokedb
      HOST_IP: 0.0.0.0
      POKEMON_CACHE: "cache/"
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start app
      run: |
        cd project/app
        docker compose version
        docker compose -f docker-compose.test.yaml up -d --build

    - name: Waiting for application
      run: |
        echo "Waiting for FastAPI to be available..."
        for i in {1..20}; do
          if curl -sSf http://localhost:8000; then
            echo "FastAPI is ready!"
            break
          fi
          sleep 3
        done

    - name: Run Playwright UI tests
      run: |
        docker build -t playwright-tests ./project/playwright/
        docker run --rm --network host playwright-tests

    - name: print docker logs
      run: |
        docker logs dexquiz -n 50
        docker logs pokedb -n 50
    
    - name: Print logs if tests fail
      if: failure()
      run: |
        docker compose -f docker-compose.test.yaml logs app
        docker compose -f docker-compose.test.yaml logs db